index:
    path: /
    controller: App\Controller\HomePageController::home

ajax:
    path: ajax.json
    controller: App\Controller\AjaxController::ajaxRequest

user-name:
    path: user-name.php
    controller: App\Controller\UserDetailsController::getUserName